# Generated by Django 5.2 on 2025-04-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_payment_status_remove_booking_room_and_more'),
        ('hotels', '0004_alter_roomtype_room_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingcartitem',
            unique_together={('booking', 'room_type')},
        ),
        migrations.AlterModelTable(
            name='bookingcartitem',
            table='booking_cart_item',
        ),
    ]
