# Generated by Django 5.2 on 2025-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_location_alter_hotel_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
