# Generated by Django 5.2 on 2025-04-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_room_available_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
