# Generated by Django 5.2 on 2025-04-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_roomtype_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
