# Generated by Django 5.2 on 2025-05-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('hotel', 'room_type')},
        ),
    ]
