# Generated by Django 5.2 on 2025-05-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_roomtype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
    ]
